// frontend/src/app/pages/auth-callback/auth-callback.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { Router } from '@angular/router';
import { getAuth, getRedirectResult } from 'firebase/auth';

@Component({
  selector: 'app-auth-callback',
  standalone: true,
  templateUrl: './auth-callback.component.html',
  styleUrls: ['./auth-callback.component.css']
})
export class AuthCallbackComponent implements OnInit {
  private router = inject(Router);
  status: 'loading' | 'error' = 'loading';
  errorMessage = '';

  async ngOnInit() {
    try {
      const auth = getAuth();
      const cred = await getRedirectResult(auth);
      if (cred?.user) {
        // Successfully signed in — navigate to dashboard.
        this.router.navigateByUrl('/dashboard');
      } else {
        // No redirect result (user landed here directly) — send back to auth.
        this.router.navigateByUrl('/auth');
      }
    } catch (err: any) {
      console.error('OAuth callback error:', err);
      this.status = 'error';
      this.errorMessage = err.message || 'Sign-in failed. Please try again.';
      // After a short delay, redirect back to auth with the error.
      setTimeout(() => this.router.navigateByUrl('/auth'), 3000);
    }
  }
}

<div class="callback-page">
  @if (status === 'loading') {
    <div class="callback-card">
      <div class="spinner"></div>
      <p class="callback-msg">Completing sign-in&hellip;</p>
    </div>
  }
  @if (status === 'error') {
    <div class="callback-card">
      <div class="error-icon">
        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="10"/>
          <line x1="12" y1="8" x2="12" y2="12"/>
          <line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
      </div>
      <p class="callback-msg">{{ errorMessage }}</p>
      <p class="callback-sub">Redirecting back to sign-in&hellip;</p>
    </div>
  }
</div>

// frontend/src/pages/AuthCallback.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAuth, getRedirectResult } from 'firebase/auth';
import './AuthCallback.css';

export const AuthCallback: React.FC = () => {
  const navigate = useNavigate();
  const [status, setStatus] = useState<'loading' | 'error'>('loading');
  const [errorMessage, setErrorMessage] = useState('');

  useEffect(() => {
    const processCallback = async () => {
      try {
        const auth = getAuth();
        const cred = await getRedirectResult(auth);
        if (cred?.user) {
          navigate('/dashboard', { replace: true });
        } else {
          navigate('/auth', { replace: true });
        }
      } catch (err: any) {
        console.error('OAuth callback error:', err);
        setStatus('error');
        setErrorMessage(err.message || 'Sign-in failed. Please try again.');
        setTimeout(() => navigate('/auth', { replace: true }), 3000);
      }
    };

    processCallback();
  }, [navigate]);

  return (
    <div className="callback-page">
      {status === 'loading' && (
        <div className="callback-card">
          <div className="callback-spinner"></div>
          <p className="callback-msg">Completing sign-in&hellip;</p>
        </div>
      )}
      {status === 'error' && (
        <div className="callback-card">
          <div className="error-icon">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="8" x2="12" y2="12" />
              <line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
          </div>
          <p className="callback-msg">{errorMessage}</p>
          <p className="callback-sub">Redirecting back to sign-in&hellip;</p>
        </div>
      )}
    </div>
  );
};
