// frontend/src/components/FlowFieldBackground.tsx
import React, { useEffect, useRef } from 'react';

interface FlowFieldBackgroundProps {
  color?: string;
  bgColorRgb?: string;
  trailOpacity?: number;
  particleCount?: number;
  speed?: number;
  className?: string;
}

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  age: number;
  life: number;
}

export const FlowFieldBackground: React.FC<FlowFieldBackgroundProps> = ({
  color = '#818cf8',
  bgColorRgb = '0, 0, 0',
  trailOpacity = 0.15,
  particleCount = 600,
  speed = 1,
  className = '',
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const animationFrameIdRef = useRef<number>(0);
  const mouseRef = useRef({ x: -1000, y: -1000 });
  const particlesRef = useRef<Particle[]>([]);
  const dimensionsRef = useRef({ width: 0, height: 0 });

  const createParticle = (width: number, height: number): Particle => {
    return {
      x: Math.random() * width,
      y: Math.random() * height,
      vx: 0,
      vy: 0,
      age: 0,
      life: Math.random() * 200 + 100,
    };
  };

  const updateParticle = (p: Particle, width: number, height: number) => {
    const angle = (Math.cos(p.x * 0.005) + Math.sin(p.y * 0.005)) * Math.PI;

    p.vx += Math.cos(angle) * 0.2 * speed;
    p.vy += Math.sin(angle) * 0.2 * speed;

    const dx = mouseRef.current.x - p.x;
    const dy = mouseRef.current.y - p.y;
    const distance = Math.sqrt(dx * dx + dy * dy);
    const interactionRadius = 150;

    if (distance < interactionRadius) {
      const force = (interactionRadius - distance) / interactionRadius;
      p.vx -= dx * force * 0.05;
      p.vy -= dy * force * 0.05;
    }

    p.x += p.vx;
    p.y += p.vy;
    p.vx *= 0.95;
    p.vy *= 0.95;

    p.age++;
    if (p.age > p.life) {
      Object.assign(p, createParticle(width, height));
    }

    if (p.x < 0) p.x = width;
    if (p.x > width) p.x = 0;
    if (p.y < 0) p.y = height;
    if (p.y > height) p.y = 0;
  };

  const drawParticle = (p: Particle, ctx: CanvasRenderingContext2D) => {
    ctx.fillStyle = color;
    const alpha = 1 - Math.abs((p.age / p.life) - 0.5) * 2;
    ctx.globalAlpha = alpha;
    ctx.fillRect(p.x, p.y, 1.5, 1.5);
  };

  useEffect(() => {
    const container = containerRef.current;
    const canvas = canvasRef.current;
    if (!container || !canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const init = () => {
      const width = container.clientWidth;
      const height = container.clientHeight;
      dimensionsRef.current = { width, height };

      const dpr = window.devicePixelRatio || 1;
      canvas.width = width * dpr;
      canvas.height = height * dpr;
      ctx.scale(dpr, dpr);
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;

      const list: Particle[] = [];
      for (let i = 0; i < particleCount; i++) {
        list.push(createParticle(width, height));
      }
      particlesRef.current = list;
    };

    const animate = () => {
      const { width, height } = dimensionsRef.current;
      ctx.fillStyle = `rgba(${bgColorRgb}, ${trailOpacity})`;
      ctx.globalAlpha = 1;
      ctx.fillRect(0, 0, width, height);

      particlesRef.current.forEach((p) => {
        updateParticle(p, width, height);
        drawParticle(p, ctx);
      });

      animationFrameIdRef.current = requestAnimationFrame(animate);
    };

    const handleMouseMove = (e: MouseEvent) => {
      const rect = canvas.getBoundingClientRect();
      mouseRef.current.x = e.clientX - rect.left;
      mouseRef.current.y = e.clientY - rect.top;
    };

    const handleMouseLeave = () => {
      mouseRef.current.x = -1000;
      mouseRef.current.y = -1000;
    };

    const handleResize = () => {
      init();
    };

    init();
    animate();

    container.addEventListener('mousemove', handleMouseMove);
    container.addEventListener('mouseleave', handleMouseLeave);
    window.addEventListener('resize', handleResize);

    return () => {
      cancelAnimationFrame(animationFrameIdRef.current);
      container.removeEventListener('mousemove', handleMouseMove);
      container.removeEventListener('mouseleave', handleMouseLeave);
      window.removeEventListener('resize', handleResize);
    };
  }, [color, bgColorRgb, trailOpacity, particleCount, speed]);

  return (
    <div
      ref={containerRef}
      className={`neural-container ${className}`}
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        background: 'transparent',
        overflow: 'hidden',
        zIndex: 0,
      }}
    >
      <canvas
        ref={canvasRef}
        className="neural-canvas"
        style={{
          display: 'block',
          width: '100%',
          height: '100%',
        }}
      />
    </div>
  );
};

// frontend/src/app/components/ui/flow-field-background.component.ts
import { Component, ElementRef, Input, ViewChild, AfterViewInit, OnDestroy, HostListener, Inject, PLATFORM_ID } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';

@Component({
  selector: 'app-flow-field-background',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div #container class="neural-container">
      <canvas #canvas class="neural-canvas"></canvas>
    </div>
  `,
  styles: [`
    .neural-container {
      position: absolute;
      top: 0; left: 0;
      width: 100%; height: 100%;
      background: transparent;
      overflow: hidden;
      z-index: 0;
    }
    .neural-canvas {
      display: block;
      width: 100%;
      height: 100%;
    }
  `]
})
export class FlowFieldBackgroundComponent implements AfterViewInit, OnDestroy {
  @ViewChild('canvas') canvasRef!: ElementRef<HTMLCanvasElement>;
  @ViewChild('container') containerRef!: ElementRef<HTMLDivElement>;

  @Input() color: string = '#818cf8';
  @Input() bgColorRgb: string = '0, 0, 0';
  @Input() trailOpacity: number = 0.15;
  @Input() particleCount: number = 600;
  @Input() speed: number = 1;

  private animationFrameId: number = 0;
  private particles: any[] = [];
  private width: number = 0;
  private height: number = 0;
  private mouse = { x: -1000, y: -1000 };
  private ctx: CanvasRenderingContext2D | null = null;
  private isBrowser: boolean;

  constructor(@Inject(PLATFORM_ID) platformId: Object) {
    this.isBrowser = isPlatformBrowser(platformId);
  }

  ngAfterViewInit() {
    if (!this.isBrowser) return;
    
    this.ctx = this.canvasRef.nativeElement.getContext('2d');
    if (!this.ctx) return;

    this.init();
    this.animate();
  }

  ngOnDestroy() {
    if (this.animationFrameId) {
      cancelAnimationFrame(this.animationFrameId);
    }
    if (this.isBrowser && this.containerRef) {
      const container = this.containerRef.nativeElement;
      container.removeEventListener("mousemove", this.onMouseMove);
      container.removeEventListener("mouseleave", this.onMouseLeave);
    }
  }

  @HostListener('window:resize')
  onResize() {
    if (this.isBrowser && this.containerRef) {
      this.init();
    }
  }

  private onMouseMove = (e: MouseEvent) => {
    if (!this.canvasRef) return;
    const rect = this.canvasRef.nativeElement.getBoundingClientRect();
    this.mouse.x = e.clientX - rect.left;
    this.mouse.y = e.clientY - rect.top;
  }

  private onMouseLeave = () => {
    this.mouse.x = -1000;
    this.mouse.y = -1000;
  }

  private init() {
    const container = this.containerRef.nativeElement;
    const canvas = this.canvasRef.nativeElement;
    
    this.width = container.clientWidth;
    this.height = container.clientHeight;
    
    const dpr = window.devicePixelRatio || 1;
    canvas.width = this.width * dpr;
    canvas.height = this.height * dpr;
    if (this.ctx) {
      this.ctx.scale(dpr, dpr);
    }
    canvas.style.width = `${this.width}px`;
    canvas.style.height = `${this.height}px`;

    this.particles = [];
    for (let i = 0; i < this.particleCount; i++) {
      this.particles.push(this.createParticle());
    }

    container.addEventListener("mousemove", this.onMouseMove);
    container.addEventListener("mouseleave", this.onMouseLeave);
  }

  private createParticle() {
    return {
      x: Math.random() * this.width,
      y: Math.random() * this.height,
      vx: 0,
      vy: 0,
      age: 0,
      life: Math.random() * 200 + 100
    };
  }

  private updateParticle(p: any) {
    const angle = (Math.cos(p.x * 0.005) + Math.sin(p.y * 0.005)) * Math.PI;
    
    p.vx += Math.cos(angle) * 0.2 * this.speed;
    p.vy += Math.sin(angle) * 0.2 * this.speed;

    const dx = this.mouse.x - p.x;
    const dy = this.mouse.y - p.y;
    const distance = Math.sqrt(dx * dx + dy * dy);
    const interactionRadius = 150;

    if (distance < interactionRadius) {
      const force = (interactionRadius - distance) / interactionRadius;
      p.vx -= dx * force * 0.05;
      p.vy -= dy * force * 0.05;
    }

    p.x += p.vx;
    p.y += p.vy;
    p.vx *= 0.95;
    p.vy *= 0.95;

    p.age++;
    if (p.age > p.life) {
      Object.assign(p, this.createParticle());
    }

    if (p.x < 0) p.x = this.width;
    if (p.x > this.width) p.x = 0;
    if (p.y < 0) p.y = this.height;
    if (p.y > this.height) p.y = 0;
  }

  private drawParticle(p: any, ctx: CanvasRenderingContext2D) {
    ctx.fillStyle = this.color;
    const alpha = 1 - Math.abs((p.age / p.life) - 0.5) * 2;
    ctx.globalAlpha = alpha;
    ctx.fillRect(p.x, p.y, 1.5, 1.5);
  }

  private animate = () => {
    if (!this.ctx) return;
    this.ctx.fillStyle = `rgba(${this.bgColorRgb}, ${this.trailOpacity})`; 
    this.ctx.fillRect(0, 0, this.width, this.height);

    this.particles.forEach((p) => {
      this.updateParticle(p);
      this.drawParticle(p, this.ctx!);
    });

    this.animationFrameId = requestAnimationFrame(this.animate);
  }
}
